apiVersion: v1
kind: Service
metadata:
  name: tarea8-service-jjlr
  labels:
    app: tarea8-jjlr
    alumno: jjlr
    curso: devops-uax-2026
spec:
  selector:
    app: tarea8-jjlr
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30080
